# Generated by Django 4.0.3 on 2022-04-04 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todo_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='todo',
            name='Folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.folder'),
        ),
    ]
