# Generated by Django 4.0.3 on 2022-04-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_todo_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='Name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
