# Generated by Django 4.0.3 on 2022-04-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_alter_folder_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='Name',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='Name',
            field=models.CharField(max_length=40),
        ),
    ]
